<?php

/**
 * @file
 * Contains myjsonmigrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function myjsonmigrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the myjsonmigrate module.
    case 'help.page.myjsonmigrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example of API Json data migration') . '</p>';
      return $output;

    default:
  }
}
